const mongoose= require('mongoose');

const FaltasSchema = mongoose.Schema({
    nombreAlumno: String,
        grupoAlumno:String,
        nombreProfessor:String,
        fechaAtencion:String,
        horaAtencion:String,
        fechaIncidente:String,
        horaIncidente:String,
        lugarIncidente:String,
        DescripcionIncidente:String,
        tipoDocumento:String,
        documentoGrave:String,
        documentoLeve:String,
        checkboxA:String,
        checkboxB:String,
        checkboxC:String,
        checkboxD:String, 
        checkboxE:String,
        checkboxF:String,
        Tareas:String,
        horaRealizacion:String,
        ExtraescolaresIni:String,
        ExtraescolaresFin:String,
        Asignaturas:String,
        SuspensionIni:String,
        SupsensionFin:String,
        TipificacionA:String,
        TipificacionB:String,
        TipificacionC:String,
        TipificacionD:String,
        TipificacionE:String,
        TipificacionF:String,
        TipificacionG:String,
        TipificacionH:String,
        TipificacionI:String,
        TipificacionJ:String,
        TipificacionK:String,
        TipificacionL:String,
        TipificacionM:String,
        TipificacionN:String,
        TipificacionÑ:String,
        TipificacionO:String,
        TipificacionP:String,
        TipificacionQ:String,
        TipificacionR:String,
        TipificacionS:String,
        Tipificacion1A:String,
        Tipificacion1B:String,
        Tipificacion1C:String,
        Tipificacion1D:String,
        Tipificacion1E:String,
        Tipificacion1F:String,
        Tipificacion1G:String,
        Tipificacion1H:String,
        Tipificacion1I:String,
        Tipificacion1J:String,
        Tipificacion1K:String,
        Tipificacion1L:String,
        Tipificacion1M:String,
        Tipificacion1N:String,
        Tipificacion1Ñ:String,
        Tipificacion1O:String,
        Tipificacion1P:String,
        Lunes:String,
        Martes:String,
        Miercoles:String,
        Jueves:String,
        Viernes:String,
        Lunes1:String,
        Martes1:String,
        Miercoles1:String,
        Jueves1:String,
        Viernes1:String,
        Eliminada:Boolean,
        FechaEliminacion:String,   
             
},{
    timestamps:true
});


module.exports = mongoose.model('Faltas',FaltasSchema);